// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  project_details: dynamic(() => import("./ProjectDetails")),
  techlist: dynamic(() => import("./Techlist")),
  text_block: dynamic(() => import("./TextBlock")),
};
